import { Checkbox, Table } from "flowbite-react"
import Head from "next/head";
import { useState } from "react";
import Layout from "~/components/layout";
import { api } from "~/utils/api";

const Members = () => {
    const query = api.mailchimp.getAllMembers.useQuery();
    console.log(query.data?.memberListArray[1]);

    return (
        <>
            <Head>
                <title>Manage Members</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className=" bg-gray-700 min-h-screen">
                <Layout>
                    <Table hoverable={true}>
                        <Table.Head className="bg-gray-800 text-white">
                            <Table.HeadCell className="!p-4">
                                <Checkbox />
                            </Table.HeadCell>
                            <Table.HeadCell>
                                Name
                            </Table.HeadCell>
                            <Table.HeadCell>
                                Email
                            </Table.HeadCell>
                            <Table.HeadCell>
                                Subscribed To
                            </Table.HeadCell>
                        </Table.Head>
                        <Table.Body className="divide-y">
                            {query.data?.memberListArray.map((e: any) =>
                                <Table.Row className="text-white border-white">
                                    <Table.Cell className="!p-4">
                                        <Checkbox />
                                    </Table.Cell>
                                    <Table.Cell className="font-medium">
                                        {e.name}
                                    </Table.Cell>
                                    <Table.Cell>
                                        {e.email}
                                    </Table.Cell>
                                    <Table.Cell>

                                    </Table.Cell>
                                </Table.Row>
                            )}
                        </Table.Body>
                    </Table>
                </Layout>
            </main >
        </>
    )
}

export default Members;