import { Table } from "flowbite-react"
import Head from "next/head";
import Layout from "~/components/layout";
import { api } from "~/utils/api";

const Members = () => {
    const query = api.mailchimp.getAllMembers.useQuery();
    console.log(query);

    return (
        <>
            <Head>
                <title>Manage Members</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Table>
                    <Table.Head>
                        <Table.HeadCell>
                            Name
                        </Table.HeadCell>
                        <Table.HeadCell>
                            Email
                        </Table.HeadCell>
                        <Table.HeadCell>
                            Subscribed To
                        </Table.HeadCell>
                        <Table.HeadCell>
                            <span className="sr-only">
                                Edit
                            </span>
                        </Table.HeadCell>
                    </Table.Head>
                    <Table.Body className="divide-y">
                    </Table.Body>
                </Table>
            </Layout>
        </>
    )
}

export default Members;